import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import HeaderNav from "./components/HeaderNav/HeaderNav";

const poppins = Poppins({ weight: ["300", "400", "600"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NOTUBE's CHILD",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <HeaderNav />
        {children}
      </body>
    </html>
  );
}
