import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const poppins = Poppins({ weight: ["300", "400"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NOTUBE's CHILD",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <header>
          <Link href="/">
            <h1>noTube</h1>
          </Link>
          <nav>
            <ul>
              <Link href="/">Pagina de Inicio</Link>
            </ul>
            <ul>
              <Link href="/">Preguntas Frecuentes</Link>
            </ul>
            <ul>
              <Link href="/">Sitios Compatibles</Link>
            </ul>
            <ul>
              <Link href="/">Blog</Link>
            </ul>
          </nav>
        </header>
        <div className="header-filler" />
        {children}
      </body>
    </html>
  );
}
